### PR TITLE
Get Context from parent view

### LINKED ISSUE #11: Inflating using the default context - does not use the application theme.
When using the recycler view - the items inflated in the recycler-view do now have the same theme as the application.

screenshot_2015-07-14-10-54-22

### PR DESCRIPTION
**Pull request by roideuniverse**
When inflating a view use the context of its parent.

Closes #11

### CODE REVIEW

**Comment by BrandonRomano** [comment]
:+1:

**Comment by kylemac** [comment]
does this close #11 ?

**Comment by roideuniverse** [comment]
@kylemac Damn missed it!

**Comment by kylemac** [comment]
:cop:

**Pull request merged**
